import '../globals.css'
export const metadata = {
  title: 'Exercisde Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>Hello</nav>
        {children}
      </body>
    </html>
  )
}
